.PHONY: clean All

All:
	@echo "----------Building project:[ 1_4_karger_min_cut - Debug ]----------"
	@cd "Week4" && "$(MAKE)" -f  "1_4_karger_min_cut.mk"
clean:
	@echo "----------Cleaning project:[ 1_4_karger_min_cut - Debug ]----------"
	@cd "Week4" && "$(MAKE)" -f  "1_4_karger_min_cut.mk" clean
