.PHONY: clean All

All:
	@echo "----------Building project:[ 2_4_Hashtable - Debug ]----------"
	@cd "Week4" && "$(MAKE)" -f  "2_4_Hashtable.mk"
clean:
	@echo "----------Cleaning project:[ 2_4_Hashtable - Debug ]----------"
	@cd "Week4" && "$(MAKE)" -f  "2_4_Hashtable.mk" clean
