.PHONY: clean All

All:
	@echo "----------Building project:[ 4_4_2SATviaSCC - Debug ]----------"
	@cd "Week4" && "$(MAKE)" -f  "4_4_2SATviaSCC.mk"
clean:
	@echo "----------Cleaning project:[ 4_4_2SATviaSCC - Debug ]----------"
	@cd "Week4" && "$(MAKE)" -f  "4_4_2SATviaSCC.mk" clean
