.PHONY: clean All

All:
	@echo "----------Building project:[ 3_4_Knapsack - Debug ]----------"
	@cd "Week4" && "$(MAKE)" -f  "3_4_Knapsack.mk"
clean:
	@echo "----------Cleaning project:[ 3_4_Knapsack - Debug ]----------"
	@cd "Week4" && "$(MAKE)" -f  "3_4_Knapsack.mk" clean
